### ISSUE TITLE
v2: Core logic overhaul

### ISSUE THREAD

**Issue by AlexStormwood** [AlexStormwood/UnityAutomatedSemver#11]
This action will be overhauled to use this package at its core: 
- https://github.com/BigfootDS/unity-semver-updater

# In Brief:

- you can use whatever version string format you like, as long as it uses the same data from semver in some way (eg. `banana-{major}-purple***{patch}` is valid since it uses major and patch data, but `banana-{banana}-purple***{purple}` is invalid since it uses no semver data.
- inputs for this action will be overhauled. Explained further below.
- it'll be easier to iterate on this action, since I foresee the Unity versioning logic aspect of this action needing more work than the actual GitHub Action aspect of this action. Platforms are inconsistent in how they version.

# Inputs will be overhauled

I'm currently looking at:
- Set some values to something specific regardless of any other package logic
  - major (number)
  - minor (number)
  - patch (number)
  - quad (number)
  - revision (number)
  - build (number)
  - releaseLabel (string)
  - buildLabel (string)
- Further control over how some data is set (eg. most people should want patch to be the same as build, as this means that a string like 1.2.3 for PC platforms and 1.2.3.0 for Xbox platforms both use the number "3" as their third number - variable names are different because they're different in the Unity documentation, so this just helps them stay in sync.)
  - treatBuildAsPatch (boolean)
  - treatRevisionAsQuad (boolean)
- Automatically increment values, or forcibly increment just one property at a time
  - updateMode (enum of major, minor, patch, quad, auto)
- Control how the version string is structured. A custom-formatted string can be applied to generate a version string in whatever structure you want. You can override that in many places. You could set one string as the generic, usual version/bundleVersion, or you can set multiple strings with different formats all at once.
  - In a generic sense:  
    - versionFormatString (general-purpose string applicable to most Unity platforms)
    - bundleVersionFormatString (alias of versionFormatString)
  - In a per-platform sense, so you can set appropriate version strings for multiple platforms in a single run of this workflow:  
    - switchDisplayVersionFormatString (same rules as versionFormatString)
    - ps4MasterVersion (string like "1.2")
    - ps4AppVersion (string like "1.2")
    - psp2MasterVersion (same rules as ps4MasterVersion)
    - psp2AppVersion (same rules as ps4AppVersion)
    - metroPackageVersion (string like "1.2.3.0")
    - XboxOneVersion (same rules as metroPackageVersion)

# To-Do List

- [x] core logic for custom-format version strings
- [x] implement inputs to match the package's customisation options
- [x] Think of more to-do list items

# Summary 

It's getting late, this has been a fun Sunday of development, will add more to this as more is developed.

But basically: this action will be a wrapper for a package that does the heavy lifting for the version string manipulation.
